### ISSUE TITLE
Через файл fifo кадры видео передаются со смещением

### ISSUE THREAD

**Issue by IlyaPetrovM** [IlyaPetrovM/AutoCam#5]
Я пишу программу на OpenCV, которая вырезает фрагмент кадра из изображения. После обрезки кадры записываются в fifo. Параллельно я запускаю vlc, который читает fifo и стримит поток, куда нужно. 
**Проблема:**
Итоговое изображение сдвигается на несколько пикселей и в результате вся картинка отображается неправильно. Сдвиг происходит каждый раз на разное количество пикселей. 
 
Вот такой получается картинка:
![Вот какой получается картинка](https://cloud.githubusercontent.com/assets/6277090/23061419/d7799150-f512-11e6-8994-db648d615ed5.png)

Смещение происходит именно при записи в fifo. Раньше я просто передавал кадры через std::cout и картинка не смещалась.

Вот фрагменты программы ([полный исходный код](https://github.com/IlyaPetrovM/AutoCam/blob/a3d7d9fcffed31ae775c99b36cb75b385a47102d/main.cpp))
```c++
int fifvideo;
        if(streamToStdOut){     
        if(!mkfifo("fifvideo",O_NONBLOCK|S_IRWXU))
        {
                cerr<<"could not create fifo fifvideo"<<endl;   
                return -1; 
        }
        fifvideo = open("fifvideo",O_RDWR,S_IRWXU);
        if(fifvideo<0){cerr<<"Could not open fifvideo"<<endl;return -1;}
/* --- many code ---- */

for(;;){

/* --- many code ---- */

if(streamToStdOut){
 Mat array = result.reshape(0,1);
 string outstr((char *)array.data,array.total()*array.elemSize());
 write(fifvideo,outstr.c_str(),outstr.length());
}

}	
```

**Comment by asalnikov** [comment]
Илья, а можно конкретную ссылку на конкретный файл, конкретного репозитория?

**Comment by IlyaPetrovM** [comment]
Вот, пожалуйста: https://github.com/IlyaPetrovM/AutoCam/blob/a3d7d9fcffed31ae775c99b36cb75b385a47102d/main.cpp#L503

**Comment by IlyaPetrovM** [comment]
Проблема заключалась в том, что я записывал всё как строку:
```c++
string outstr((char *)array.data,array.total()*array.elemSize());
```
При записи абсолютно чёрного цвета у меня получался признак конца строки вот здесь: 
```c++
write(fifvideo,
outstr.c_str(), // <- here was the problem
outstr.length());
```
Кроме того, поведение системного вызова ```write``` очень ненадёжно. Если записывать туда большую картинку, то она заблокирует весь поток вывода, а может и неполностью отработать (записать только часть данных и выкинуть исключение).

В общем, я отказался от преобразования в строку и от ``write ``. 
Проблема решена в комите: 
https://github.com/IlyaPetrovM/AutoCam/commit/df6ff29411da1c34fcd0887fc33c263228c68b49

```c++

void stream(Mat mat, fstream &f){ 
  if(!mat.empty()) 
  for (Pixel &p : cv::Mat_<Pixel>(mat)) 
  { 
   f << p.x; f << p.y; f << p.z; //color components: Blue, Green and Red
} 
f.flush();
}
void streamInThread(const char *filename, Mat* mat, bool* finish = new bool(0)){ 
 fstream fifoFdRes; int fifresult=0; try{ 
 unlink(filename); 
 fifresult = mkfifo(filename,O_RDWR|S_IRWXU|O_NONBLOCK);
 fifoFdRes.open(filename,fstream::out|fstream::trunc); 
 while(!(*finish)){ 
  if(mat!=NULL) { 
  stream(mat->clone(),fifoFdRes); 
  } 
} }catch(exception e){ 
cerr << e.what() <<endl; 
} 
  fifoFdRes.close();
 unlink(filename); 
 clog << "thread " << filename << " finished" << endl;
}

```


Спасибо, Алексею Сальникову за помощь!
